#theme: minima
title: Peter's Maths Blog
author: Peter Moskvichev
description: My first attempt to write a blog on my GitHub website
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
