theme: jekyll-theme-dinky
title: Peter's Maths Blog
author: Peter Moskvichev
description: My first attempt to write a blog on my GitHub website
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
