theme: minima
title: Peter's Maths Blog
author: Peter Moskvichev
description: My first attempt to write a blog on my GitHub website
markdown: GFM
kramdown:
  input: Kramdown
math_engine: mathjax
